### ISSUE TITLE
Since september 9 or 10, update of tables is wrong

### ISSUE THREAD

**Issue by hsarrazin** [Pascalco/recentdeaths#4]
On year tables, items with p570 set should be removed when the bot updates the lists, but it is not done correctly anymore https://www.wikidata.org/w/index.php?title=Wikidata:Database_reports/Deaths_at_Wikipedia/2017&diff=556356850&oldid=556290008

only 10 items should remain, but 129, completed yesternight are left on the list.

Could you please check the problem ? (it is the same with all year lists, not only 2017).

Thanks

**Comment by Pascalco** [comment]
resolved by switching the hosting cluster for the repo database
